---
  name: Build and Test
  
  on:
    pull_request:
      branches: [main]
      paths:
        - '**/Dockerfile'
        - '**/.dockerignore'
        - .github/**
        - '**.go'
        - '**.mod'
        - '**.sum'
        - config/**
        - '**/Makefile*'
        - '**/documentation.md'
        - .golangci.yaml
        - .goreleaser.yaml
  
    push:
      branches: [main]
  
  jobs:
    go-semantic-release:
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on:
        group: bigger
      permissions:
        contents: write
      steps:
        - name: Clone repository
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            fetch-depth: 0
        - name: Get next version
          id: get_next_version
          uses: thenativeweb/get-next-version@f9202b1ab94b345e7ca86da624762a5e17d4cd3e # v2.6.2
          with:
            prefix: v   # optional, defaults to ''
        - name: Show the next version
          run: |
            echo ${{ steps.get_next_version.outputs.version }}
        - name: Install tools
          run: make install-tools
        - name: Update VERSION file
          run: |
            new_version=${{ steps.get_next_version.outputs.version }}
            sed -i "s/version: .*/version: ${new_version}/" versions.yaml
        - name: Multimod prerelease
          run: make multimod-prerelease
        - name: Generate a token
          id: generate_token
          uses: actions/create-github-app-token@v1
          with:
            app_id: ${{ secrets.APP_ID }}
            private_key: ${{ secrets.APP_PRIVATE_KEY }}
            owner: ${{ github.repository_owner }}
  
        - name: Run go-semantic-release
          uses: go-semantic-release/action@v1
          with:
            github-token: ${{ steps.generate_token.outputs.token }}
            changelog-generator-opt: emojis=true
            allow-initial-development-versions: true
  